### ISSUE TITLE
Footer changes

### ISSUE THREAD

**Issue by Dulyaaa** [sliitwomeninfoss/wif-web#26]
Do following changes to footer:

![image](https://user-images.githubusercontent.com/57215584/142234002-33e67a95-cec8-4529-a662-d123ef7c82bf.png)

- [ ] Remove YouTube icon
- [ ] Link to pages(Home, About Us etc...)
- [ ] Remove links of GitHub, Leaderboard, etc.. and Home, Terms, etc... 
- [ ] Change WIF into `SLIIT Women In FOSS`

**Comment by Modeesha-Kalani** [comment]
All changes are made in the new PR.
