### ISSUE TITLE
Word changes

### ISSUE THREAD

**Issue by Dulyaaa** [sliitwomeninfoss/wif-web#65]
Need to update the following words accordingly: 

- ### **Women `In` FOSS**

> _In AboutUs Page_

- [ ] ![image](https://user-images.githubusercontent.com/57215584/145072064-236663e0-5bba-4051-87ad-b38c5a73995b.png)

- [ ] ![image](https://user-images.githubusercontent.com/57215584/145072133-605c96cc-28ed-4930-b33e-732bb17cfd33.png)

- ### **SLIIT Women In FOSS Community**
> _In Footer_
- [ ] ![image](https://user-images.githubusercontent.com/57215584/145072213-c274a839-05e6-4762-9b1f-0dc6dc7dcda9.png)

- ### **SLIIT Women In FOSS Community** | **Women `In` FOSS** 

> _In Home Page (Mascot Section)_
- [ ] ![image](https://user-images.githubusercontent.com/57215584/145072448-74c85a46-d428-45e4-980a-39dd46c0c8cc.png)

**Comment by DerekJxy** [comment]
Hi there! Can I try this one?
